#!/bin/bash

# This script is used to build the F2MD project
# It takes an optional argument -s to specify the step to build

USAGE="Usage: $0 [-s <step>]"
USAGE+="\n\nOptions:"
USAGE+="\n  -s <step>  Specify the step to build."
USAGE+="\n     Available value for steps are:"
USAGE+="\n         py-req"
USAGE+="\n         inet"
USAGE+="\n         veins"
USAGE+="\n         veins_inet3"
USAGE+="\n         simulte"
USAGE+="\n         all"
USAGE+="\n     Default is all."


# Disclaimer
echo "This script is used to build the F2MD project."
echo "and requires the following to be already installed:"
echo "    1. SUMO"
echo "    2. OMNeT++"

F2MD_DIR=$(pwd)
STEP="all"

while getopts ":s:" opt; do
  case $opt in
    s)
      STEP=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
        echo -e $USAGE
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# Install f2md dependencies
if [[ $STEP == "py-req" || $STEP == "all" ]]; then
    echo "################ Install Python, net-tools, gnuplot etc. ####################"
    sudo apt install -y python3-dev python3-tk net-tools gnuplot rapidjson-dev
    
fi

if [[ $STEP == "inet" || $STEP == "all" ]]; then
    # Build Inet
    echo "######################### Building inet #########################"
    cd ./inet
    export INET_ROOT=${F2MD_DIR}/inet
    echo $INET_ROOT
    export PATH="${INET_ROOT}/bin:${PATH}"
    export INET_NED_PATH="${INET_ROOT}/src:${INET_ROOT}/tutorials:${INET_ROOT}/showcases:${INET_ROOT}/examples"
    export INET_OMNETPP_OPTIONS="-n ${INET_NED_PATH} --image-path=${INET_ROOT}/images"
    export INET_GDB_OPTIONS="-quiet -ex run --args"
    export INET_VALGRIND_OPTIONS="-v --tool=memcheck --leak-check=yes --show-reachable=no --leak-resolution=high --num-callers=40 --freelist-vol=4000000"
    make makefiles && make -j$(nproc) WITH_OSGEARTH=no MODE=debug && make -j$(nproc) MODE=release all
fi

if [[ $STEP == "veins" || $STEP == "all" ]]; then
    # Build veins
    echo "######################### Building veins #########################"
    cd ${F2MD_DIR}/veins-f2md
    rm -rf ${F2MD_DIR}/veins-f2md/out
    ./configure
    make -j$(nproc) MODE=release all
fi

if [[ $STEP == "veins_inet3" || $STEP == "all" ]]; then
    # Build veins_inet3
    echo "######################### Building veins_inet3 #########################"
    cd ${F2MD_DIR}/veins-f2md/subprojects/veins_inet3
    rm -rf ${F2MD_DIR}/veins-f2md/subprojects/veins_inet3/out
    ./configure && make -j$(nproc) MODE=release all
fi

if [[ $STEP == "simulte" || $STEP == "all" ]]; then
    # Build simulte
    echo "######################### Building simulte #########################"
    cd ${F2MD_DIR}/simulte-f2md
    rm -rf ${F2MD_DIR}/simulte-f2md/out
    make makefiles
    make -j$(nproc) MODE=release all
fi
